name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
      - name: Verify environment variables
        run: |
          echo "ACTIONS_ID_TOKEN_REQUEST_URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"

      - name: Get the OIDC token
        id: oidc-token
        run: |
          OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
              "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          echo "OIDC_TOKEN=$OIDC_TOKEN" >> $GITHUB_ENV
