name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
      - name: Get the OIDC token
        id: oidc-token
        run: |
          echo "OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
              "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')" >> $GITHUB_ENV

      - name: Use the OIDC token
        run: |
          echo "OIDC Token: $OIDC_TOKEN"
